### ISSUE TITLE
Date Filters not working

### ISSUE THREAD

**Issue by Dnhatsave** [howkymike/alfresco-workflow-summary#1]
Hi @howkymike , 

I've this addon working on Alfresco 6.1.2 GA, when i tried to use the **startedAfter** and **startedBeforee** filter the server response with 200 but i cant see any reports of documents started due this interval as you can see 
![Screenshot from 2021-02-16 14-20-52](https://user-images.githubusercontent.com/43370602/108050342-28426080-7052-11eb-92cb-6600fc3747c3.png)
.No log is show on alfresco side.

do you know how can i solve this problem ??

Thank you.

**Comment by howkymike** [comment]
Hi @Dnhatsave,
startedBefore date is BEFORE startedAfter date so it an impossible date. You probably confused startedAfter with the endedBefore argument (which i did not expose, but pull requests are welcome).

**Comment by wessrafamessi** [comment]
hi @Dnhatsave  how did you deployed the [alfresco-workflow-summary) and how it work ?

**Comment by Dnhatsave** [comment]
@howkymike  yeah i figure out that the filter are inverted :-D but i've fix that and now it works.

@wessrafamessi  well i just follow the read me but i didn't  run **mvn clean package** to build the amp files istead i run the mvn comand without test like this **mvn clean install -DskipTests** 

i hope this is useful.
Cheers

**Comment by wessrafamessi** [comment]
HI , where did you put the deploy the download files ? if you are available can we have a call to help me 
thank you
